name: item_scanner

packages:
  - packages/*
  - example

sdkPath: .fvm/flutter_sdk

scripts:
  analyze:
    run: melos exec -- "dart analyze ."
    description: Run `dart analyze` in all packages.

  test:
    run: melos exec --dir-exists="test" -- "flutter test"
    description: Run `flutter test` for selected packages.

  version:
    run: melos version
    description: Generate changelogs and version packages.

  build:android:
    run: melos exec --scope="item_scanner" -- "fvm flutter build apk --release"
    description: Build Android release APK for example app.

  build:android:aab:
    run: melos exec --scope="item_scanner" -- "fvm flutter build appbundle --release"
    description: Build Android release App Bundle (.aab) for example app.

  build:ios:
    run: melos exec --scope="item_scanner" -- "fvm flutter build ipa --release"
    description: Build iOS release IPA (requires macOS/Xcode/signing).

  build:web:
    run: melos exec --scope="item_scanner" -- "fvm flutter build web --release"
    description: Build Web release for example app.
